
export const products = [
  {
    id: 1,
    name: "Midnight Muse Bodycon",
    price: 1999,
    category: "Women",
    type: "Topwear",
    image: "https://images.pexels.com/photos/6311396/pexels-photo-6311396.jpeg",
    description: "Elegant black dress for all occasions.",
    rating: 4.5,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 2,
    name: "Blush Bloom Bodycon",
    price: 1999,
    category: "Women",
    type: "Topwear",
    image: "https://images.pexels.com/photos/1027130/pexels-photo-1027130.jpeg",
    description: "Floral pink bodycon for brunch or evenings.",
    rating: 4.3,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 3,
    name: "Noir Nights Mini Bodycon",
    price: 1999,
    category: "Women",
    type: "Topwear",
    image: "https://images.pexels.com/photos/6311611/pexels-photo-6311611.jpeg",
    description: "Chic black mini perfect for date nights.",
    rating: 4.6,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 4,
    name: "Pastel Muse Bodycon",
    price: 2999,
    category: "Women",
    type: "Winterwear",
    image: "https://images.pexels.com/photos/1542085/pexels-photo-1542085.jpeg",
    description: "Soft pastel tones meet winter elegance.",
    rating: 4.4,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 5,
    name: "Crimson Chic Dress",
    price: 2499,
    category: "Women",
    type: "Bottomwear",
    image: "https://images.pexels.com/photos/6311374/pexels-photo-6311374.jpeg",
    description: "Bold crimson for the confident woman.",
    rating: 4.2,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 6,
    name: "Royal Velvet Dress",
    price: 2799,
    category: "Women",
    type: "Topwear",
    image: "https://images.pexels.com/photos/6311376/pexels-photo-6311376.jpeg",
    description: "Luxurious velvet dress in royal tones.",
    rating: 4.7,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 7,
    name: "Urban Vibe Hoodie",
    price: 1499,
    category: "Men",
    type: "Winterwear",
    image: "https://images.pexels.com/photos/2535859/pexels-photo-2535859.jpeg",
    description: "Comfy hoodie for city chillers.",
    rating: 4.1,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 8,
    name: "Essential Street Tee",
    price: 899,
    category: "Men",
    type: "Topwear",
    image: "https://images.pexels.com/photos/220560/pexels-photo-220560.jpeg",
    description: "Everyday tee with essential style.",
    rating: 4.0,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 9,
    name: "Cozy Gray Sweatshirt",
    price: 1299,
    category: "Men",
    type: "Winterwear",
    image: "https://images.pexels.com/photos/614018/pexels-photo-614018.jpeg",
    description: "Stay warm and stylish in gray.",
    rating: 4.3,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 10,
    name: "Classic Black Joggers",
    price: 1599,
    category: "Men",
    type: "Bottomwear",
    image: "https://images.pexels.com/photos/974470/pexels-photo-974470.jpeg",
    description: "Classic joggers for comfort and fit.",
    rating: 4.5,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 11,
    name: "Kiddo Dino Hoodie",
    price: 999,
    category: "Kids",
    type: "Winterwear",
    image: "https://images.pexels.com/photos/3661553/pexels-photo-3661553.jpeg",
    description: "Fun hoodie with dinosaur print for kids.",
    rating: 4.6,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 12,
    name: "Sunny Day T-shirt",
    price: 699,
    category: "Kids",
    type: "Topwear",
    image: "https://images.pexels.com/photos/1382731/pexels-photo-1382731.jpeg",
    description: "Bright yellow tee perfect for playtime.",
    rating: 4.2,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 13,
    name: "Chill Vibes Shorts",
    price: 799,
    category: "Kids",
    type: "Bottomwear",
    image: "https://images.pexels.com/photos/3661556/pexels-photo-3661556.jpeg",
    description: "Light and comfy shorts for summer days.",
    rating: 4.4,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 14,
    name: "Luxe Lavender Dress",
    price: 2199,
    category: "Women",
    type: "Topwear",
    image: "https://images.pexels.com/photos/1488463/pexels-photo-1488463.jpeg",
    description: "Lavender vibes with luxe appeal.",
    rating: 4.6,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 15,
    name: "Citrus Pop Blazer",
    price: 2399,
    category: "Women",
    type: "Topwear",
    image: "https://images.pexels.com/photos/6311582/pexels-photo-6311582.jpeg",
    description: "Stand out in this citrus color blazer.",
    rating: 4.3,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 16,
    name: "Choco Fudge Jacket",
    price: 2699,
    category: "Men",
    type: "Winterwear",
    image: "https://images.pexels.com/photos/5322206/pexels-photo-5322206.jpeg",
    description: "Chocolate-toned jacket with cozy feel.",
    rating: 4.5,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 17,
    name: "Neon Zip Trackpant",
    price: 1599,
    category: "Men",
    type: "Bottomwear",
    image: "https://images.pexels.com/photos/5325882/pexels-photo-5325882.jpeg",
    description: "Pop out with neon accent joggers.",
    rating: 4.4,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 18,
    name: "Pinkie Party Dress",
    price: 2099,
    category: "Kids",
    type: "Topwear",
    image: "https://images.pexels.com/photos/1101730/pexels-photo-1101730.jpeg",
    description: "Adorable pink party dress for little stars.",
    rating: 4.7,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 19,
    name: "Royal Blue Blouse",
    price: 1899,
    category: "Women",
    type: "Topwear",
    image: "https://images.pexels.com/photos/1852385/pexels-photo-1852385.jpeg",
    description: "Classy royal blue blouse for all occasions.",
    rating: 4.5,
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: 20,
    name: "Mint Flow Shirt",
    price: 999,
    category: "Men",
    type: "Topwear",
    image: "https://images.pexels.com/photos/5325857/pexels-photo-5325857.jpeg",
    description: "Flowy mint green shirt for sunny days.",
    rating: 4.2,
    sizes: ["S", "M", "L", "XL"]
  },
    {
      id: 21,
      image: "../../public/collection/1.jpg",
      name: "Dreamscape",
      artist: "Nova Beats",
      rating: 4.8,
      price: 1999,
      genre: "Electronic",
      tag: "Top Charts",
      sizes: ["S", "M", "L", "XL"],
      description: "An ethereal blend of electronic rhythms for dreamers."
    },
    {
      id: 22,
      image: "../../public/collection/2.jpg",
      name: "Midnight Rain",
      artist: "Luna Sky",
      rating: 4.6,
      price: 1249,
      genre: "Pop",
      tag: "New Release",
      sizes: ["S", "M", "L", "XL"],
      description: "Smooth pop beats that feel like a late-night rain shower."
    },
    {
      id: 23,
      image: "../../public/collection/3.jpg",
      name: "Vibe Avenue",
      artist: "DJ Mirage",
      rating: 4.7,
      price: 2229,
      genre: "Hip-Hop",
      tag: "Trending",
      sizes: ["S", "M", "L", "XL"],
      description: "Hip-hop street vibes to elevate your daily grind."
    },
    {
      id: 24,
      image: "../../public/collection/4.jpg",
      name: "Echoes of Time",
      artist: "Celeste Harmony",
      rating: 4.9,
      price: 2449,
      genre: "Classical",
      tag: "Editor's Pick",
      sizes: ["S", "M", "L", "XL"],
      description: "Timeless classical melodies to relax and reflect."
    },
    {
      id: 25,
      image: "../../public/collection/5.jpg",
      name: "Urban Pulse",
      artist: "Rhythm X",
      rating: 4.4,
      price: 1999,
      genre: "Rap",
      tag: "Hot Now",
      sizes: ["S", "M", "L", "XL"],
      description: "Raw and real rap rhythms from the urban core."
    },
    {
      id: 26,
      image: "../../public/collection/6.jpg",
      name: "Sunset Drive",
      artist: "Neon Drift",
      rating: 4.5,
      price: 1579,
      genre: "Synthwave",
      tag: "Top 10",
      sizes: ["S", "M", "L", "XL"],
      description: "A synthwave soundtrack perfect for your evening cruise."
    },
    {
      id: 27,
      image: "../../public/collection/7.jpg",
      name: "Heartbeats",
      artist: "Amber Rose",
      rating: 4.3,
      price: 1229,
      genre: "Romance",
      tag: "Soft Vibes",
      sizes: ["S", "M", "L", "XL"],
      description: "Romantic ballads that tug at your heartstrings."
    },
    {
      id: 28,
      image: "../../public/collection/8.jpg",
      name: "Desert Storm",
      artist: "Echo Nomad",
      rating: 4.6,
      price: 2109,
      genre: "World",
      tag: "Cultural Picks",
      sizes: ["S", "M", "L", "XL"],
      description: "World fusion music inspired by desert winds."
    },
    {
      id: 29,
      image: "../../public/collection/9.jpg",
      name: "Firelight",
      artist: "Ignite",
      rating: 4.7,
      price: 1559,
      genre: "Rock",
      tag: "Classic Hit",
      sizes: ["S", "M", "L", "XL"],
      description: "Fiery rock anthems that spark your inner rebel."
    },
    {
      id: 30,
      image: "../../public/collection/10.jpg",
      name: "Neon Jungle",
      artist: "Bass Tribe",
      rating: 4.8,
      price: 2019,
      genre: "EDM",
      tag: "Festival Vibes",
      sizes: ["S", "M", "L", "XL"],
      description: "High-energy EDM beats for party animals."
    },
    {
      id: 31,
      image: "../../public/collection/3.jpg",
      name: "Vibe Avenue",
      artist: "DJ Mirage",
      rating: 4.7,
      price: 2229,
      genre: "Hip-Hop",
      tag: "Trending",
      sizes: ["S", "M", "L", "XL"],
      description: "Hip-hop street vibes to elevate your daily grind."
    },
  
];
